### ISSUE TITLE
`add_font` should support an explicit path instead only a filename

### ISSUE THREAD

**Issue by Xtrem532** [PyFPDF/fpdf2#101] opened 2021-02-03 15:18 UTC
Specifically, https://github.com/PyFPDF/fpdf2/blob/6511eb02bd38acfd871e299cb781052f4fd0c73f/fpdf/fpdf.py#L573-L580 makes it impossible to add fonts from arbitrary locations without changing the working directory or setting the `SYSTEM_TTFONTS` constant.

This was possible in PyFPDF by just passing the path as str (see https://github.com/reingart/pyfpdf/blob/cb3340806c140b6e63eb4ce9d6230be84fba456e/fpdf/fpdf.py#L491-L492 ).

Bonus points for support of Path-Like Objects instead of just str.

**Comment by Lucas-C** [comment] 2021-02-03 15:29
Hi and thanks for reporting this @Xtrem532!

I added a test for `add_font` last week, post release `2.3.0`, using a `Path` object:
https://github.com/PyFPDF/fpdf2/blob/master/test/fonts/test_add_font.py#L29

I also made a minor fix, that maybe could haved fixed your issue:
https://github.com/PyFPDF/fpdf2/commit/d8a5b019c4b0a410628e0f0670473b9ba7a6b188

Hence:
- could you provide some minimal Python code reproducing your issue please?
- could try it with the latest version of `fpdf2` from the `master` branch of this repo?

    pip install git+https://github.com/PyPDF/fpdf2.git@master

**Comment by Lucas-C** [comment] 2021-02-03 15:42
I added a new test and all seems OK: https://github.com/PyFPDF/fpdf2/commit/dd7d7aff55bdb8d322e1cbb5cc355fac4f475471

Hence, could you provide some minimal Python code reproducing your issue please?

**Comment by Xtrem532** [comment] 2021-02-03 15:59
I see - support *should* be there, the Path concatonation with "." threw me off.
The real problem is that if `FPDF_CACHE_MODE` is set to 2, https://github.com/PyFPDF/fpdf2/blob/dd7d7aff55bdb8d322e1cbb5cc355fac4f475471/fpdf/fpdf.py#L2387-L2390 gets a path object, raising
```
  [...]
  File "C:\[Redacted]\env\lib\site-packages\fpdf\fpdf.py", line 585, in add_font
    unifilename = FPDF_CACHE_DIR / f"{_hashpath(ttffilename)}.pkl"
  File "C:\[Redacted]\env\lib\site-packages\fpdf\fpdf.py", line 2405, in _hashpath
    h.update(fn.encode("UTF-8"))
AttributeError: 'WindowsPath' object has no attribute 'encode'
```

**Comment by Xtrem532** [comment] 2021-02-03 16:13
Just wrapping `fn` in a `str()` call worked for me: 
```python
def _hashpath(fn):
    h = md5()
    h.update(str(fn).encode("UTF-8"))
    return h.hexdigest()
```

**Comment by Lucas-C** [comment] 2021-02-04 13:29
Out of curiosity, how did you set `FPDF_CACHE_MODE`?

**Comment by Lucas-C** [comment] 2021-02-04 13:54
Also, I plan to get rid of this cache mode in https://github.com/PyFPDF/fpdf2/pull/103

**Comment by Xtrem532** [comment] 2021-02-04 15:46
Its not private, so its really strightforward to set:

```python
from fpdf import fpdf
[...]
fpdf.FPDF_CACHE_MODE = 2
fpdf.FPDF_CACHE_DIR = fontcache_path
```

BTW, I really dislike how PyFPDF2 has the  same modulename as PyFPDF1 - it just is not a drop in replacement at this point, and being one would hold it back anyway, so just accept the API incompatibilities and rename it.
That would also enable things like

```python
using_fpdf2: bool
try:
    from fpdf2.fpdf import [things]
    using_fpdf2 = True
except ImportError:
    from fpdf.fpdf import [things]
    using_fpdf2 = False
```
which is way less hacky then trying to use the versionnumber to detect if we are using 1 or 2.

**Comment by alexanderankin** [comment] 2021-02-04 16:21
`pyfpdf` is effectively deprecated because as far as i know the only maintainer with commit and publish access has not published since 2015 and insists on 2.7 support because there are apps he built the application for which use python2.

Which is to say I'm comfortable reusing the import name even if its not a perfect replacement. Right now somethings are broken because of the changes necessary to modernize this library. modernizing the library is necessary in the long run anyways. We have also fixed a lot of bugs in the old library too.

For the record, i think the cache should stay for now, for backwards compatibility and also while there is no proper font library to obviate the need for pre-processing.

**Comment by Lucas-C** [comment] 2021-02-04 16:23
The cache is enabled by default and will stay, it's just cache mode 2 that this PR aims to get rid of 😊

**Comment by Lucas-C** [comment] 2021-02-12 08:47
Done in https://github.com/PyFPDF/fpdf2/pull/103

Closing

**Closed by Lucas-C** 2021-02-12 08:47 UTC
Labels: bug, pending-answer
