### ISSUE TITLE
Number of pages appears to not function correctly

### ISSUE THREAD

**Issue by slightlynybbled** [PyFPDF/fpdf2#71] opened 2021-01-19 12:12 UTC
This worked in `fpdf`.

I have an object that I created called `_Report` that subclasses `fpdf`:

```python
from pathlib import Path
from fpdf import FPDF


class _Report(FPDF):
    def __init__(self, title: str):
        super().__init__()

        self._title = title
        self._user_documents = Path('.').absolute()

        ypos = 50
        xpos = 10
        self.set_x(xpos)
        self.set_y(ypos)
        self.set_font('Arial', 'B', 12)

        self.add_page()
        self.alias_nb_pages()

        self.saved_as = None

    def create_report(self, save_path=None):
        if save_path is None:
            save_as = self._user_documents
        else:
            save_as = save_path

        save_as = save_as / 'report.pdf'

        self.output(save_as, 'F')
        self.saved_as = save_as

    def header(self):
        pos = 30
        self.set_y(pos)
        self.cell(0, 0, 'Organization Name')

        self.set_y(pos + 8)
        self.cell(0, 0, self._title)

    def footer(self):
        self.set_y(-15)
        # Page number
        self.cell(0, 10, f'Page {self.page_no()} of ' + '{nb}', 0, 0, 'C')


if __name__ == '__main__':
    rp = _Report(title='test title')
    rp.create_report()
```

I have tried several items for that last line in the `footer` to no avail.  I have also tried to move the `self.alias_nb_pages()` to a couple of different locations, but it always prints "{nb}" on to the PDF.

**Comment by Lucas-C** [comment] 2021-01-19 12:42
Your snippet does include how to initialize & use your custom class.
After trying to use it, I realized that `_user_documents` refers to an undefined attribute, and that the call to `set_font` in `__init_` must be done before `add_page`

Could you please provide code that is directly usable to reproduce your issue ?

**Comment by slightlynybbled** [comment] 2021-01-19 12:55
You are correct.  I tried to strip things a bit to the bone and ended up making my example un-runnable.  My bad.  I have updated the snipped to represent a minimal example.

Thank you for your assistance,

j

**Comment by Lucas-C** [comment] 2021-01-19 14:02
I had to slightly modify your `create_report` method:
```python
    def create_report(self, save_path=None):
        if save_path is None:
            save_as = self._user_documents
        with (save_as / 'report.pdf').open('wb') as report_file:
            self.output(report_file)
```
But it works:
![2021-01-19 15_01_11-report pdf - SumatraPDF](https://user-images.githubusercontent.com/925560/105044683-4cb51800-5a67-11eb-929b-f4fc4b629197.png)

**Comment by slightlynybbled** [comment] 2021-01-19 14:03
When you say "it works", that looks exactly like it doesn't work.  I'm expecting to see "Page 1 of 1".

**Comment by Lucas-C** [comment] 2021-01-19 14:41
This is the text string used in the `footer` method: `f'Page {self.page_no()} of ' + '{nb}'`

This is where your issue come from.

Try this instead:
```python
self.cell(0, 10, f'Page {self.page_no()} of {len(self.pages)}', 0, 0, 'C')
```

**Comment by Lucas-C** [comment] 2021-01-19 14:46
The workaround I mentioned above should work for you,
but this is indeed a bug with old `alias_nb_pages` feature.

I'm going to take a look at it soon in order to replicate the original functionality.

**Comment by slightlynybbled** [comment] 2021-01-19 17:36
Perfect workaround.  Thank you!

I don't want to hit "close" b/c it appears that you are tracking this as a bug, but feel free to close when you feel that the issue is resolved.

**Comment by Lucas-C** [comment] 2021-01-19 18:15
Thanks. This will be automatically closed when https://github.com/PyFPDF/fpdf2/pull/72 will be merged.

Also, a side note: I noticed your "trick" to avoid f-string substitution of the "{nb}' alias.
Note that an alternative is to double the curly braces: `f"{{nb}}"` 😉

**Comment by slightlynybbled** [comment] 2021-01-19 18:17
I agree.  I had initially done that, but in my attempts to correct the issue, I tried a few things.  I prefer f-strings, but I was at my wit's end.

**Comment by Lucas-C** [comment] 2021-01-19 18:27
Closed by https://github.com/PyFPDF/fpdf2/pull/72

**Closed by Lucas-C** 2021-01-19 18:27 UTC
Labels: bug

**Comment by msmannan00** [comment] 2024-05-21 20:53
Hi Lucas,

I am speaking from Globaleaks. I am having an issue with the footer:
def footer(self):
    self.set_y(-15)
    self.set_font(self.report_default_font, '', 12)
    self.set_text_shaping(use_shaping_engine=True, direction="ltr")
    self.cell(0, 10, f"{self.page_no()}/{{nb}}", align="C")
    self.set_text_shaping(use_shaping_engine=True, direction=self.report_direction)

I have a lot of custom fonts. All work perfectly while generating the PDF, but {{nb}} doesn't get replaced if I use custom fonts and is printed as 1/{nb}. However, if I use your default fonts like Courier, it works as expected, replacing {nb} with total pages.

strange thing is while using custom fonts font of 1/{nb} is also changed its just that the {nb} is not replaced with total page

**Comment by andersonhc** [comment] 2024-05-21 22:07
> Hi Lucas,
> 
> I am speaking from Globaleaks. I am having an issue with the footer: def footer(self): self.set_y(-15) self.set_font(self.report_default_font, '', 12) self.set_text_shaping(use_shaping_engine=True, direction="ltr") self.cell(0, 10, f"{self.page_no()}/{{nb}}", align="C") self.set_text_shaping(use_shaping_engine=True, direction=self.report_direction)
> 
> I have a lot of custom fonts. All work perfectly while generating the PDF, but {{nb}} doesn't get replaced if I use custom fonts and is printed as 1/{nb}. However, if I use your default fonts like Courier, it works as expected, replacing {nb} with total pages.
> 
> strange thing is while using custom fonts font of 1/{nb} is also changed its just that the {nb} is not replaced with total page

It is a known issue, reported on #1090 because text shaping with render the {nb} differently with some fonts depending specially on kerning.

I am going to work on this issue soon and we will hopefully have a final solution before the next release.

In the meantime I can suggest 2 workarounds:
* Using a different font on your footer
* Using a different page number alias - i.e. calling self.alias_nb_pages(alias="####") and writing f"{self.page_no()}/####" on your trailer

**Comment by evilaliv3** [comment] 2024-05-22 06:36
Thank you @andersonhc , we have solved using 'courier' for the header and footers actually works for us since it adds a nice touch to result we need in @globaleaks.

This is actually the issue i was encountering with @msmannan00 while working on https://github.com/py-pdf/fpdf2/discussions/1175#discussioncomment-9506693
