### ISSUE TITLE
Provide a working example, on how to put an image into a table.

### ISSUE THREAD

**Issue by eabase** [PyFPDF/fpdf2#681] opened 2023-02-05 22:17 UTC
Hi, 
I'm trying to put an image into a table but can't find any examples or documentation on how to do so. 
Please provide some working examples with clear visual output.

**Comment by Lucas-C** [comment] 2023-02-06 10:08
Hi @eabase and welcome

Istn't this issue a duplicate of #680 ?
If so, no need to open multiple issues in this project.
I'm going to close one of them unless you calrify how they are different.

**Closed** 2023-02-11 19:00 UTC
Labels: duplicate, enhancement, pending-answer
