### ISSUE TITLE
Need support to display URL output inside a table cell

### ISSUE THREAD

**Issue by Rahulscan** [PyFPDF/fpdf2#763] opened 2023-04-11 07:45 UTC
I want to display a QR code inside a table cell which is the output of a URL.

``` python
pdf.image('https://my.gstzen.in/.............../a/invoices/.......................qrcode/.png/)
with pdf.table(col_widths=(33.3, 33.4, 33.3), first_row_as_headings=False, markdown=True) as table:
     row.cell(pdf.image)
```
OR
``` Python
x = pdf.image('https://my.gstzen.in/.............../a/invoices/.......................qrcode/.png/)
with pdf.table(col_widths=(33.3, 33.4, 33.3), first_row_as_headings=False, markdown=True) as table:
     row.cell(x)
```

**An error is being displayed - AttributeError: 'function' object has no attribute 'encode'**

Can anyone suggest what should be done ?

**Comment by Lucas-C** [comment] 2023-04-11 11:50
Hi @Rahulscan and welcome!

We users report bug, we ask them to provide some contextual information in order to be able to help them:
https://raw.githubusercontent.com/PyFPDF/fpdf2/master/.github/ISSUE_TEMPLATE/bug_report.md

In this case, without some minimal code reproducing your error, I cannot really help you much...
Could you at least specify the full error stacktrace, and if the error happens during the call to `pdf.image()`, or on `row.cell()` ?

Anyway your code cannot posibly work because, as stated in our documentation, images must be inserted using `row.cell(img=...)`: https://pyfpdf.github.io/fpdf2/Tables.html#insert-images

**Comment by Rahulscan** [comment] 2023-04-12 04:14
**Error details**
Traceback (most recent call last):
  File "/Users/rahulsharma/PycharmProjects/pdf1/PDF.py", line 19, in <module>
    with pdf.table(col_widths=(33.3, 33.4, 33.3), first_row_as_headings=False, markdown=True) as table:
  File "/usr/local/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py", line 144, in __exit__
    next(self.gen)
  File "/Users/rahulsharma/PycharmProjects/pdf1/PDF/lib/python3.11/site-packages/fpdf/fpdf.py", line 4715, in table
    table.render()
  File "/Users/rahulsharma/PycharmProjects/pdf1/PDF/lib/python3.11/site-packages/fpdf/table.py", line 99, in render
    self._render_table_row(i)
  File "/Users/rahulsharma/PycharmProjects/pdf1/PDF/lib/python3.11/site-packages/fpdf/table.py", line 166, in _render_table_row
    lines_heights_per_cell = self._get_lines_heights_per_cell(i)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rahulsharma/PycharmProjects/pdf1/PDF/lib/python3.11/site-packages/fpdf/table.py", line 289, in _get_lines_heights_per_cell
    self._render_table_cell(
  File "/Users/rahulsharma/PycharmProjects/pdf1/PDF/lib/python3.11/site-packages/fpdf/table.py", line 248, in _render_table_cell
    lines = self._fpdf.multi_cell(
            ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rahulsharma/PycharmProjects/pdf1/PDF/lib/python3.11/site-packages/fpdf/fpdf.py", line 261, in wrapper
    return fn(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rahulsharma/PycharmProjects/pdf1/PDF/lib/python3.11/site-packages/fpdf/fpdf.py", line 3459, in multi_cell
    txt = self.normalize_text(txt)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rahulsharma/PycharmProjects/pdf1/PDF/lib/python3.11/site-packages/fpdf/fpdf.py", line 4105, in normalize_text
    return txt.encode(self.core_fonts_encoding).decode("latin-1")
           ^^^^^^^^^^
AttributeError: 'ImageInfo' object has no attribute 'encode'


**Minimal code**
```python
pdf.image('https://my.gstzen.in/.............../a/invoices/.......................qrcode/.png/)
with pdf.table(col_widths=(33.3, 33.4, 33.3), first_row_as_headings=False, markdown=True) as table:
     row.cell(pdf.image)
```
or
```python
x = pdf.image('https://my.gstzen.in/.............../a/invoices/.......................qrcode/.png/)
with pdf.table(col_widths=(33.3, 33.4, 33.3), first_row_as_headings=False, markdown=True) as table:
     row.cell(x)
```

If there is any other information you need, please let me know !!

**Comment by gmischler** [comment] 2023-04-12 06:47
> **Minimal code**
> 
> ```python
> pdf.image('https://my.gstzen.in/.............../a/invoices/.......................qrcode/.png/)
> with pdf.table(col_widths=(33.3, 33.4, 33.3), first_row_as_headings=False, markdown=True) as table:
>      row.cell(pdf.image)
> ```

`pdf.image` is a method of the FPDF  class. Using that as an argument to the text parameter of `row.cell()` makes no sense whatsoever.
(Note that your example will also throw a SyntaxError, because of the malformed URL string.)

Have you read all of @Lucas-C´s reply above? He has already given you the solution, as well as a link to the relevant section of the documentation:
```... images must be inserted using row.cell(img=...).```
https://pyfpdf.github.io/fpdf2/Tables.html#insert-images

In your case, the correct use is very simple and straightforward:

`    row.cell(img="https://www.example.com/qrcode.png")`

**Comment by Rahulscan** [comment] 2023-04-12 06:51
Hi @gmischler , @Lucas-C 
Yes @Lucas-C reply worked. Thanks for reaching out !!

**Comment by Lucas-C** [comment] 2023-04-12 07:00
Glad that fixed you problem 😊

And thank you @gmischler for helping out!

Closing this issue now

**Closed by Lucas-C** 2023-04-12 07:00 UTC
Labels: bug, pending-answer, table, link
