### ISSUE TITLE
write_html() does not generate proper cell border if a cell contains a multi line text.

### ISSUE THREAD

**Issue by nova-03** [PyFPDF/fpdf2#370] opened 2022-03-20 15:23 UTC
If a cell contains multi line text, then write_html() will generate the proper table, but some cell borders will be missing as marked red in this screenshot:

![image](https://user-images.githubusercontent.com/101177440/159169594-3d035d7c-d4e9-48e0-9a5d-4afc84198841.png)

Code for reproducing this bug:
```Pyhton
        data = (
                ("First name", "Last name", "Age", "City"),
                ("Jules", "Smith", "34", "San Juan"),
                ("Mary", "Ramos Saint Mahturin<br>sur Loire", "45", "Orlando"),
                ("Carlson", "Banks", "19", "Los Angeles"),
                ("Lucas", "Cimon", "31", "Saint Mahturin sur Loire<br>Saint Mahturin sur Loire <br>Saint Mahturin sur Loire <br>Saint Mahturin sur Loire"),
               )
            
        pdf.write_html(
                      f"""<table border="1">
                            <thead>
                              <tr>
                                <th width="25%">{data[0][0]}</th>
                                <th width="25%">{data[0][1]}</th>
                                <th width="15%">{data[0][2]}</th>
                                <th width="35%">{data[0][3]}</th>
                              </tr>
                            </thead>
                            <tbody>
                              <tr><td>{'</td><td>'.join(data[1])}</td></tr>
                              <tr><td>{'</td><td>'.join(data[2])}</td></tr>
                              <tr><td>{'</td><td>'.join(data[3])}</td></tr>
                              <tr><td>{'</td><td>'.join(data[4])}</td></tr>
                            </tbody>
                          </table>""",
                      table_line_separators=True,
                      )

```

**Comment by Lucas-C** [comment] 2022-03-21 07:19
Thanks for reporting this @nova-03 
I'll have a look at it soon

**Comment by Lucas-C** [comment] 2022-03-22 21:13
OK, I think this is a duplicate of https://github.com/PyFPDF/fpdf2/issues/91

Do you agree @nova-03?

**Comment by nova-03** [comment] 2022-03-22 21:46
> Do you agree @nova-03?

Yes.

Since this is a missing feature I think it would be good thing to document the current limitations of write_html() as long as we don't have it implemented.

**Comment by Lucas-C** [comment] 2022-03-23 06:05
Feel free to submit a PR 😊

Maybe we could document that there: https://pyfpdf.github.io/fpdf2/HTML.html

Closing as duplicate

**Closed by Lucas-C** 2022-03-23 06:05 UTC
Labels: bug, pending-answer, html-mixin

**Comment by nova-03** [comment] 2022-03-23 10:47
> Feel free to submit a PR 😊

Since I do not have the exact knowledge of this and other limitations of the current implementation, in my opinion, I am not the right person to document it.
Besides that, in this case I think that one sentence like "Currently multi-line text in table cells is not supported." would suffice. Creating a PR for such a small change is a bit overhead, so I suggest that you insert it by yourself if you agree.

> Maybe we could document that there: https://pyfpdf.github.io/fpdf2/HTML.html

Yes, that would be a perfect place for the limitation note.

**Comment by Lucas-C** [comment] 2022-03-29 14:32
I added a mention to the docs: https://github.com/PyFPDF/fpdf2/blob/master/docs/HTML.md#supported-html-features

**Comment by nova-03** [comment] 2022-03-29 18:19
Great, thank you!
