### ISSUE TITLE
How to make words(font) more thicker than normal bold type of a font?

### ISSUE THREAD

**Issue by kargan49** [PyFPDF/fpdf2#369] opened 2022-03-17 15:54 UTC
How to make words(font) more thicker than normal bold type of a font?

**Comment by Lucas-C** [comment] 2022-03-17 17:23
Use another, thicker, font? 😊

**Comment by Lucas-C** [comment] 2022-03-17 19:06
No, not currently.
Some custom fonts includes shadows though: [Bower Shadow](https://www.dafont.com/fr/bower-shadow.font), [Deep Shadow](https://www.dafont.com/fr/deep-shadow.font)...

**Comment by Lucas-C** [comment] 2022-03-18 12:44
Note [that section 9.2.3 of the PDF spec](https://www.adobe.com/content/dam/acom/en/devnet/pdf/pdfs/PDF32000_2008.pdf), _Achieving Special Graphical Effects_, describe some intersting visual effects that can be applied to text, by combining font operators with general graphics operators:

![PDFSpecAchievingSpecialGraphicalEffects](https://user-images.githubusercontent.com/925560/159004987-8a917d6c-6807-4130-b88f-a51508dd6e2c.png)

@kargan49 would you be interested in contributing such feature to `fpdf2`?
Otherwise, do you have any other questions, or can this issue be closed?

**Comment by Lucas-C** [comment] 2022-03-19 12:30
As a starting point, there is some code that reproduce the effect in Figure 37 above:
```python
import fpdf
pdf = fpdf.FPDF()
pdf.add_page()
pdf.set_font("Helvetica", size=200)
pdf._out("BT 80 600 Td 1 Tr 2 w (ABC) Tj ET")
pdf.output("text-outline.pdf")
```

**Comment by kargan49** [comment] 2022-03-19 14:58
![Originalpng](https://user-images.githubusercontent.com/62643624/159126169-f0b74437-f2b1-41f8-b0b9-224f6e3d65e3.png)
![Replicate](https://user-images.githubusercontent.com/62643624/159126173-cf9259b6-1ca7-4f9a-ad77-a157c8522bdc.png)
I want to replicate a pdf document. The document had font style as 'Helvetica', bold with font size 12.  When I replicated both doesn't seem to be alike.

**Comment by kargan49** [comment] 2022-03-19 15:02
> As a starting point, there is some code that reproduce the effect in Figure 37 above:
> 
> ```python
> import fpdf
> pdf = fpdf.FPDF()
> pdf.add_page()
> pdf.set_font("Helvetica", size=200)
> pdf._out("BT 80 600 Td 1 Tr 2 w (ABC) Tj ET")
> pdf.output("text-outline.pdf")
> ```
> 
> Compared to `pdf.write("ABC")`, just a few characters have been added to the output: `1 Tr 2 w`. Those could be inserted by `FPDF._render_styled_cell_text` in order to support such text effect.

![Originalpng](https://user-images.githubusercontent.com/62643624/159126169-f0b74437-f2b1-41f8-b0b9-224f6e3d65e3.png)
![Replicate](https://user-images.githubusercontent.com/62643624/159126173-cf9259b6-1ca7-4f9a-ad77-a157c8522bdc.png)
The image at the top is from original document and the bottom image is the replicated pdf using FPDF2.

I want to replicate a pdf document. The document had font style as 'Helvetica', bold with font size 12.  When I replicated both doesn't seem to be alike. The font in the orginal document seem to be bolder than the replicated one.

Any help would be appreciated.

**Comment by Lucas-C** [comment] 2022-03-19 15:27
Have you tried using Helvetica Bold instead? (maybe from [here](https://freefontsfamily.com/helvetica-bold-font-free/) or [here](https://github.com/CartoDB/cartodb/blob/master/app/assets/fonts/helvetica-bold.ttf))

**Comment by kargan49** [comment] 2022-03-19 17:11
> Have you tried using a `.ttf` font that is close to Helvetica, but thicker?
> Maybe **Helvetica Bold**, _e.g._ from [here](https://freefontsfamily.com/helvetica-bold-font-free/) or [here](https://github.com/CartoDB/cartodb/blob/master/app/assets/fonts/helvetica-bold.ttf)?

I tried those, even that didn't work.

**Comment by Lucas-C** [comment] 2022-03-19 17:24
How did that not work? You did not get the exact similar visual?
How have you identified the font?

**Comment by kargan49** [comment] 2022-03-21 12:39
> How did that not work? You did not get the exact similar visual?
> How have you identified the font?

The font is still lighter than the original one.

**Comment by kargan49** [comment] 2022-03-22 05:56
> OK, then:
> 
> * short term, if you want to use `fpdf2`, your best option is probably to use an external editor tool for font files that will allow you to craft a font with the thickness you require, based on Helvetica. I won't be able to help more about this.
> 
> * medium term, we could add support for selecting **text rendering mode** to `fpdf2`:
> ![TextRenderingModes](https://user-images.githubusercontent.com/925560/159265053-9d318483-3d30-46f9-aa51-d7d50034afc1.jpg)
> 
> I'm considering the following API for `FPDF.write()` / `FPDF.cell()` / `FPDF.multi_cell()`:
> ```python
> pdf.cell(txt="Hello world", mode=FillStroke(stroke=2))
> ```
> 
> Alternatives could be:
> ```python
> pdf.set_text_mode(FillStroke, stroke=2)
> pdf.cell(txt="Hello world")
> ```
> 
> Or:
> ```python
> with pdf.set_text_mode(FillStroke, stroke=2):
> 	pdf.cell(txt="Hello world")
> ```
> 
> @gmischler: I'd be curious to get your opinion on this 😊
> 

Yes, this would be good option.

**Comment by gmischler** [comment] 2022-03-23 04:28
> I'm considering the following API for FPDF.write() / FPDF.cell() / FPDF.multi_cell():
>
> `pdf.cell(txt="Hello world", mode=FillStroke(stroke=2))`
>
> Alternatives could be:
> ```
>pdf.set_text_mode(FillStroke, stroke=2)
>pdf.cell(txt="Hello world")
>```
>
>Or:
>```
>with pdf.set_text_mode(FillStroke, stroke=2):
>	pdf.cell(txt="Hello world")
>```

i was wondering, if text rendering mode would come up here any time soon...

Sounds like a good idea, since it's a key feature currrently still missing.
Careful selection and naming of options will be key to make it practical.

The context manager looks like the cleanest solution.

The feature seems to be indepenent of the PDF grphics state, so a seperate method with its own global state would be bad design.

**Comment by gmischler** [comment] 2022-03-23 04:34
> The image at the top is from original document and the bottom image is the replicated pdf using FPDF2.

@kargan49, can you extract a minimal example of such an original document (that doesn't reveal any secrets!), so we can analyze how it's done, and/or which font it actually uses?

**Comment by Lucas-C** [comment] 2022-04-04 21:07
I opened https://github.com/PyFPDF/fpdf2/pull/380 to implement `set_text_mode`

Could you please review it @gmischler?

**Comment by Lucas-C** [comment] 2022-04-19 07:52
#380 has been merged and released in **v2.5.2**

@kargan49: do you still have a feature request about this, or any unanswered questions? Or can we close this issue?

**Comment by kargan49** [comment] 2022-04-23 08:53
> #380 has been merged and released in **v2.5.2**
> 
> @kargan49: do you still have a feature request about this, or any unanswered questions? Or can we close this issue?

the addition of **text_mode** in the latest update resolved my issue for thickening the font by the use of FILL_STROKE attribute, thank you for the addition of this feature.

**Comment by kargan49** [comment] 2022-04-23 08:58
How to change the line width of border line in a multicell?

**Comment by Lucas-C** [comment] 2022-04-23 10:13
> How to change the line width of border line in a multicell?

You can use [set_line_width()](https://pyfpdf.github.io/fpdf2/fpdf/fpdf.html#fpdf.fpdf.FPDF.set_line_width)

```python
pdf = FPDF()
pdf.add_page()
pdf.set_font("Helvetica", size=36)
pdf.set_line_width(3)
pdf.multi_cell(w=100, h=30, align="C", border=1, txt="Lorem ipsum")
pdf.output("multicell_with_large_border.pdf")
```

Closing this issue now

**Closed by Lucas-C** 2022-04-23 10:13 UTC
Labels: question, pending-answer, font
