### ISSUE TITLE
Create a URL link

### ISSUE THREAD

**Issue by manfredlotz** [PyFPDF/fpdf2#64] opened 2021-01-18 15:12 UTC
In html I could have `<a href="url">link text</a>`. Is there a possibility to have a kindof `link(..)` function which writes such a link to pdf? Something like `link_external("link text", "url")`

The `link()` function I found does only link to some other place in the pdf document.

Thank you.

**Comment by Lucas-C** [comment] 2021-01-18 17:55
This really require some more documentation, so thanks for asking :)

This is how you can create a URL link:
```python
pdf.link(x, y, width, height, "https://github.com/PyFPDF/fpdf2")
```

For an link internal to the document, it is a bit more convoluted:
```python
link = pdf.add_link()
pdf.set_link(link, page=page_id)
pdf.link(x, y, width, height, link)
```

**Comment by Lucas-C** [comment] 2021-01-19 09:23
You can also use `write_html`: https://github.com/PyFPDF/fpdf2/blob/master/test/html/test_html.py#L54

**Comment by manfredlotz** [comment] 2021-01-20 19:11
Thanks for, `write_html` which I found as well in the meantime. 

However I was not able to get `pdf.link(x, y, width, height, "https://github.com/PyFPDF/fpdf2")` running. 
Instead I found something in the docs so that I got this working:

```
from fpdf import FPDF

class MyFPDF(FPDF):
    def hyperlink(self, link_text, url):
        self.set_text_color(70, 150, 50)
        self.set_font("helvetica", "B", 16)
        self.write(5, 'pyfpdf.github.io/fpdf2/', 'https://pyfpdf.github.io/fpdf2/')

def main() -> None:
    pdf = MyFPDF()
    pdf.add_page()
    pdf.hyperlink('fpdf2', 'https://pyfpdf.github.io/fpdf2/' )
    pdf.output("test1.pdf")
```

**Comment by Lucas-C** [comment] 2021-01-21 08:31
Glad you found a solution!
Indeed, [the `write` method accepts a `link` parameter](https://pyfpdf.github.io/fpdf2/reference/write.html)

Here is an alternative example code using `FPDF.link`:
````python
from fpdf import FPDF

pdf = FPDF()
pdf.add_page()
pdf.set_font("helvetica", size=36)
line_height = 10
text = "Hello World!"
pdf.text(x=0, y=line_height, txt=text)
width = pdf.get_string_width(text)
pdf.link(x=0, y=0, w=width, h=line_height, link="https://github.com/PyFPDF/fpdf2")
pdf.output("hello.pdf")
```

I'm going to keep this is issue open as a remainder to better document this and/or add

**Comment by Lucas-C** [comment] 2021-01-29 10:24
Documented added in https://github.com/PyFPDF/fpdf2/pull/96

Closing this

**Closed by Lucas-C** 2021-01-29 10:24 UTC
Labels: documentation, question

**Comment by andersonhc** [comment] 2023-08-14 13:35
> Sorry for resurrecting this. I have some texts that may contain links. And I want to display them with pdf.cell as I want them to have the same length for all the lines. At the moment all the links are clickable but not highlighted. Is it possible to make all the links highlighted?

Hi fabmeyer
Do you want the links highlighted with underline (like HTML links) or yellow background on the link?

**Comment by fabmeyer** [comment] 2023-08-14 14:14
@andersonhc thanks for your fast reply. Highlighted with underline (like HTML) would be perfect. Is that possible with `pdf.cell`?

**Comment by andersonhc** [comment] 2023-08-14 14:21
> @andersonhc thanks for your fast reply. Highlighted with underline (like HTML) would be perfect. Is that possible with `pdf.cell`?

Try this:
```python
pdf = fpdf.FPDF()
pdf.add_page()
pdf.set_font(family="Helvetica", style="U", size=20) # underline
pdf.set_text_color(0, 0, 255) # blue text
pdf.cell(txt="fpdf2 Github", link="https://github.com/py-pdf/fpdf2")
pdf.output("link.pdf")
```

**Comment by fabmeyer** [comment] 2023-08-14 14:24
@andersonhc no that doesn't work as there are potential many different links in the same cell...

**Comment by andersonhc** [comment] 2023-08-14 14:47
> @andersonhc no that doesn't work as there are potential many different links in the same cell...

You can make multiple links underlined in `cell` using markdown:
```python
pdf.cell(txt="--link1-- blabla --link2-- abc --link3--", markdown=True)
```

**Comment by fabmeyer** [comment] 2023-08-14 14:59
@andersonhc I already tried that but it doesn't work.

`
pdf.multi_cell(w=0, h=6, txt=text, new_x="LEFT", markdown=True)
`

with text:

Trends in travel and vacation include travelers expecting more value for money, staying closer to home, and growth in travel demand in the Middle East and Europe. According to the United Nations World Tourism Organization, travelers will expect more value for money this year and are expected to stay closer to home due to financial worries and inflation. The report also said that growth in travel demand in the Middle East and Europe will be the fastest, with these two regions expected to catch up with the pre-pandemic levels this year when it comes to travel and tourism. Additionally, according to a January 2023 sentiment survey from tourism market research firm Longwoods International, about half of American travelers say financial pressures will impact their travel decisions in the coming six months, with airfare being the biggest factor. Furthermore, according to a Bloomberg report, 56% of the survey respondents said airfare is the biggest factor in this equation. This suggests that travelers are looking for more affordable options when it comes to travel and vacation. 

Furthermore, according to a CNBC report, the chaotic summer of 2022 saw airlines struggling to keep up with the demand for travel. This suggests that travelers are looking for more reliable options when it comes to travel and vacation. 

Sources: 
United Nations World Tourism Organization: https://www.unwto.org/
Longwoods International: https://longwoods-intl.com/
Bloomberg: https://www.bloomberg.com/
CNBC: https://www.cnbc.com/2022/09/09/airlines-chaotic-summer-is-over-heres-how-it-went.html

Output in PDF looks like this:

![example](https://github.com/py-pdf/fpdf2/assets/24493253/0a6f0ec7-1408-4b13-b496-26c8b9741edc)

**Comment by andersonhc** [comment] 2023-08-14 15:20
@fabmeyer 
add `--` before and after each link to add the underline

```
Sources:
United Nations World Tourism Organization: --https://www.unwto.org/--
Longwoods International: --https://longwoods-intl.com/--
Bloomberg: --https://www.bloomberg.com/--
CNBC: --https://www.cnbc.com/2022/09/09/airlines-chaotic-summer-is-over-heres-how-it-went.html--
```

**Comment by fabmeyer** [comment] 2023-08-14 16:37
@andersonhc thank you very much, underlining works now. Another issue that I have is that links that are longer than one line don't work as they get cut off and wrapped to the next line. Is it possible to fix that somehow?

**Comment by Lucas-C** [comment] 2023-08-15 21:12
> Another issue that I have is that links that are longer than one line don't work as they get cut off and wrapped to the next line. Is it possible to fix that somehow?

Thank you for reporting this @fabmeyer 😊
This may be a bug.
Could you please create a dedicated issue, with some minimal Python code reproducing this "cut off" behaviour?
