### ISSUE TITLE
Justified text is not aligned left on the last line of every paragraph in a multi-cell

### ISSUE THREAD

**Issue by gtnbssn** [PyFPDF/fpdf2#364] opened 2022-03-13 14:45 UTC
I was using 2.5.0, and when the text is justified, the last line of each paragraph was aligned left.

This looks better than justified text, given that the last line is shorter.

With 2.5.1, only the very last line of the multi-cell will be set this way. Last lines of other paragraphs will be justified, sometimes with a lot of blank space.

In the following example, this is mostly visible on page 3.

```python
from fpdf import FPDF

text = """« Jadis, si je me souviens bien, ma vie était un festin où s’ouvraient tous les cœurs, où tous les vins coulaient.

Un soir, j’ai assis la Beauté sur mes genoux. — Et je l’ai trouvée amère. — Et je l’ai injuriée.

Je me suis armé contre la justice.

Je me suis enfui. Ô sorcières, ô misère, ô haine, c’est à vous que mon trésor a été confié !

Je parvins à faire s’évanouir dans mon esprit toute l’espérance humaine. Sur toute joie pour l’étrangler j’ai fait le bond sourd de la bête féroce.

J’ai appelé les bourreaux pour, en périssant, mordre la crosse de leurs fusils. J’ai appelé les fléaux, pour m’étouffer avec le sable, le sang. Le malheur a été mon dieu. Je me suis allongé dans la boue. Je me suis séché à l’air du crime. Et j’ai joué de bons tours à la folie.

Et le printemps m’a apporté l’affreux rire de l’idiot.

Or, tout dernièrement m’étant trouvé sur le point de faire le dernier couac ! j’ai songé à rechercher la clef du festin ancien, où je reprendrais peut-être appétit.

La charité est cette clef. — Cette inspiration prouve que j’ai rêvé !

« Tu resteras hyène, etc…, » se récrie le démon qui me couronna de si aimables pavots. « Gagne la mort avec tous tes appétits, et ton égoïsme et tous les péchés capitaux. »

Ah ! j’en ai trop pris : — Mais, cher Satan, je vous en conjure, une prunelle moins irritée ! et en attendant les quelques petites lâchetés en retard, vous qui aimez dans l’écrivain l’absence des facultés descriptives ou instructives, je vous détache ces quelques hideux feuillets de mon carnet de damné. """

pdf = FPDF(format="A5")
pdf.open()
pdf.add_font("Lekton", "", "/usr/share/fonts/TTF/Lekton-Regular.ttf", uni=True)
pdf.set_font("Lekton", "", 14)
pdf.set_margins(34, 55, 34)
pdf.add_page()
pdf.set_auto_page_break(auto=True, margin=55)
pdf.multi_cell(0, None, text, align="J")
pdf.output("bug.pdf")
```

**Comment by Lucas-C** [comment] 2022-03-13 15:01
I reproduced the bug. Thanks for reporting it @gtnbssn 
There is a screenshot:
<img width="261" alt="issue_364" src="https://user-images.githubusercontent.com/925560/158065786-bc53850a-70ee-48ac-b394-8e421fea9549.png">
Ping @gmischler who worked on that part of the code

**Comment by gmischler** [comment] 2022-03-13 16:06
Thanks for the ping, @Lucas-C 

Interesting catch!
I'm guessing that this has always been the behaviour when feeding multiple paragraphs to a single call of `multi_cell()`.

Fixing it will require to look ahead for each line, to see if the line after it (if any) is empty. At least that's what I would consider a reasonable criterion for "end of paragraph". Any other ideas? Do we need an option to switch paragraph recognition on and off?

**Comment by gtnbssn** [comment] 2022-03-14 03:18
Well, it works as i would expect in version 2.5.0.

I pinned the version with pipenv: `pipenv install fpdf2==2.5.0`

And here's a screenshot of page 3:
![noBugFpdf2](https://user-images.githubusercontent.com/10359074/158098883-252d09bb-a362-42e9-b13b-04d711b016a8.png)

**Comment by gtnbssn** [comment] 2022-03-14 03:20
> Fixing it will require to look ahead for each line, to see if the line after it (if any) is empty.

Would it make more sense to check if the line ends with a line feed / carriage return? We might not always have empty lines between paragraphs.

**Comment by gmischler** [comment] 2022-03-14 10:48
> Well, it works as i would expect in version 2.5.0.

Ah I see. So I apparently threw this under the bus when adding support for soft-hyphens to `write()`.

> Would it make more sense to check if the line ends with a line feed / carriage return?

That sounds better, yes.
Looks like I was led astray by the specific example (and distracted by the weird french typography :wink:).

I had to recheck my understanding of the line wrapping code, and found some incorrect assumptions that I had made.
The new fix will make it impossible (like before) to directly force justified alignment on a line with no line break. I do it indirectly in one of my tests anyway, by replacing the affected TextLine with one that has `justify=True` set.

Is there a practical use case for justifying a single line, or the last line of a paragraph, despite the usual typographical conventions?
If so, then we might have to add an additional alignment option (say `align="X"`).

**Comment by gtnbssn** [comment] 2022-03-15 01:00
> That sounds better, yes. Looks like I was led astray by the specific example (and distracted by the weird french typography wink).

Ah indeed, i hadn't thought about this! We do have different rules which explain the space before the exclamation mark for instance... Sorry about that!

> Is there a practical use case for justifying a single line, or the last line of a paragraph, despite the usual typographical conventions? If so, then we might have to add an additional alignment option (say `align="X"`).

I am no expert so maybe others will be able to give a better opinion. But i would say no, at least not for regular typography. Maybe for a specific design? But in this case, anything goes anyway.

Here's what another library is doing: https://pdfkit.org/docs/text.html

And since they mention word processors: i don't think these offer the option you are describing.

**Comment by gmischler** [comment] 2022-03-15 12:39
>  i would say no, at least not for regular typography. Maybe for a specific design? But in this case, anything goes anyway.

I was thinking poster or label design, where a single line fit into a given width is quite common (by various means).
Do we want to limit the use of the library to regular book or magazine type flowing text?
It's not particularly hard to implement either, and maybe someone would find it useful.

> And since they mention word processors: i don't think these offer the option you are describing.

Text processors typically not, but a page layout program might.

**Comment by Lucas-C** [comment] 2022-03-19 16:05
I'd really like to include a fix for this as part of v2.5.2...
I'll get a closer look at this once @gmischler PRs are merged 😊

**Comment by gmischler** [comment] 2022-04-09 13:26
@Lucas-C, I think #350 should have fixed this one as well.
Or is there some problem still remaining?

**Comment by Lucas-C** [comment] 2022-04-10 15:27
Yes, I have just tested it and this is fixed indeed
Closing this now

**Closed by Lucas-C** 2022-04-10 15:27 UTC
Labels: bug, multi_cell, text-alignment
