### ISSUE TITLE
FPDFException( fpdf.errors.FPDFException: A page cannot be added on a closed document, after calling output()

### ISSUE THREAD

**Issue by tluanga** [PyFPDF/fpdf2#531] opened 2022-09-13 07:59 UTC
I get this error while generating a pdf .

```python
import os
from fpdf import FPDF
from apps.registration.registration_application.model import RegistrationApplication
import datetime
msu_logo_path = 'assets/msu-logo.jpg'


class RegistrationApplicationPDF(FPDF):
    def header(self):
        # Logo
        # self.image('logo_pb.png', 10, 8, 33)
        # Arial bold 15
        self.set_font('Times', 'B', 15)

        # Move to the right
        self.cell(80)
        self.image(mzu_logo_path, w=18, h=14)
        # Title
        self.cell(h=2, w=4, txt='', ln=2)
        self.cell(h=8, w=20, align='C',
                  txt="Mizoram University", border=cell_border, ln=2,)
        self.set_font('Times', 'B', 13)
        self.cell(h=7, w=20, align='C',
                  txt="Registration Application", border=cell_border, ln=2,)

        # Line break
        self.ln(20)

    # Page footer
    def footer(self):
        # Position at 1.5 cm from bottom
        self.set_y(-15)
        # Arial italic 8
        self.set_font('Arial', 'I', 8)
        # Page number
        self.cell(0, 10, 'Page ' + str(self.page_no()) + '/{nb}', 0, 0, 'C')


cell_height = 9
cell_border = 0


# --declared as global
pdf = RegistrationApplicationPDF()


def generate_test_pdf(registration_application: RegistrationApplication):
    try:
        print('generating pdf')
        print(' payload in generating pdf')
        print(registration_application)
        pdf.add_page()
        pdf.set_xy(10, 43)
        pdf.set_font('Times', '', 12)
        # ---First Row---
        pdf.set_font('Times', 'B', 12)
        pdf.cell(h=cell_height, w=40, align='',
                 txt="Application No", border=cell_border, ln=0)
        pdf.cell(h=cell_height, w=20, align='',
                 txt=":", border=cell_border, ln=0)
        pdf.set_font('Times', '', 12)
        pdf.cell(h=cell_height, w=70, align='',
                 txt=registration_application.application_id, border=cell_border, ln=0)
        pdf.set_font('Times', 'B', 12)
        pdf.cell(h=cell_height, w=20, align='',
                 txt="Date", border=cell_border, ln=0)
        pdf.cell(h=cell_height, w=10, align='',
                 txt=":", border=cell_border, ln=0)
        pdf.set_font('Times', '', 12)
        pdf.cell(h=cell_height, w=20, align='',
                 txt=registration_application.status_log[-1].date_time.strftime('%d/%m/%y'), border=cell_border, ln=1)

        pdfTextField(
            'Name', registration_application.personal_info.full_name)
        pdfTextField(
            'Fathers Name', registration_application.personal_info.fathers_name)
        pdfTextField(
            'Mothers Name', registration_application.personal_info.mothers_name)
        pdfTextField(
            'Gender', registration_application.personal_info.gender)
        pdfTextField(
            'Date of Birth', registration_application.personal_info.date_of_birth)
        pdfTextField(
            'Category', registration_application.personal_info.person_category)
        pdfTextField(
            'Nationality', registration_application.personal_info.nationality)
        pdfTextField(
            'Religion', registration_application.personal_info.religion)
        pdfTextField('Phone No',
                     str(registration_application.personal_info.mobile))
        pdfTextField(
            'Email', registration_application.personal_info.email)
        pdfTextField(
            'Permanent Address', registration_application.personal_info.permanent_address)

        # --------Mizoram University Enrollment
        pdf.set_font('Times', 'B', 12)
        pdf.cell(h=3, w=3, txt='', ln=1)
        pdf.cell(h=cell_height, w=40, align='',
                 txt='Mizoram University Enrollment - ', border=cell_border, ln=1)
        pdf.set_font('Times', '', 12)
        pdf.cell(10)
        pdfTextField(
            'Rollno', registration_application.academic_info.mzu_rollno)
        pdf.cell(10)
        pdfTextField(
            'Admission Batch', registration_application.academic_info.admission_batch.name)
        pdf.cell(10)
        pdfTextField(
            'Programme', registration_application.academic_info.programme.name)

        # --------Last Examination passed infor
        pdf.set_font('Times', 'B', 12)
        pdf.cell(h=3, w=3, txt='', ln=1)
        pdf.cell(h=cell_height, w=40, align='',
                 txt='Last Examination Passed- ', border=cell_border, ln=1)
        pdf.set_font('Times', '', 12)
        pdf.cell(10)
        pdfTextField(
            'Rollno', registration_application.academic_info.rollno_of_last_exam_passed)
        pdf.cell(10)
        pdfTextField(
            'year', str(registration_application.academic_info.year_of_last_exam_passed))
        pdf.cell(10)
        pdfTextField(
            'Board/University', registration_application.academic_info.board_university_of_last_exam_passed)

        # --------Last Examination passed infor
        pdf.set_font('Times', 'B', 12)
        pdf.cell(h=3, w=3, txt='', ln=1)
        pdf.cell(h=cell_height, w=40, align='',
                 txt='Class X- ', border=cell_border, ln=1)
        pdf.set_font('Times', '', 12)
        pdf.cell(10)
        pdfTextField(
            'Rollno', registration_application.academic_info.class_x_rollno)
        pdf.cell(10)
        pdfTextField(
            'year', str(registration_application.academic_info.year_of_x_exam_passed))
        pdf.cell(10)
        pdfTextField(
            'Board', registration_application.academic_info.class_x_board)
        print('output the file')
        pdf.output('test.pdf', 'F')
        if os.path.exists('test.pdf'):
            return 'test.pdf'
        else:
            return 'ERROR'
    except:
        print('pdf generation error')


def pdfTextField(label: str, value: str):
    pdf.set_font('Times', 'B', 12)
    pdf.cell(h=cell_height, w=40, align='',
             txt=label, border=cell_border, ln=0)
    pdf.cell(h=cell_height, w=20, align='', txt=":", border=cell_border, ln=0)
    pdf.set_font('Times', '', 12)
    pdf.cell(h=cell_height, w=80, align='',
             txt=value, border=cell_border, ln=1)

```

**Comment by semaeostomea** [comment] 2022-09-13 08:50
I can't see you calling `generate_test_pdf()` anywhere. Is it possible you're trying to call it more than once sometime later in your code that is not included here? You opened the pdf before defining `generate_test_pdf()`, which means that if you call that function twice, it will throw that exact error since the pdf if you opened before has been closed by the first call to `generate_test_pdf()`

**Comment by Lucas-C** [comment] 2022-09-13 08:51
Hi @tluanga and welcome here!
You did right to come here for help.
However you eem to have skipped some steps in the issue template,
notable the part about providing a **minimal** reproducible example:
https://github.com/PyFPDF/fpdf2/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by tluanga** [comment] 2022-09-13 10:14
The problem is that sometimes the code works and some times it is not, I call the function from an async function, I am sure I call it once

**Comment by semaeostomea** [comment] 2022-09-13 10:22
try moving `pdf = RegistrationApplicationPDF()` into the `generate_test_pdf` function.

If you do that you also need to move the `pdfTextField` function into that function or pass `pdf` to it because it will throw an error otherwise

**Comment by Lucas-C** [comment] 2022-09-13 11:12
> The problem is that sometimes the code works and some times it is not, I call the function from an async function, I am sure I call it once

Could you please reduce your code snippet to the bare minimum that triggers your issue?

**Comment by Lucas-C** [comment] 2022-09-20 08:58
Unless an update is made on this issue in the following week, I'm planning to close it

**Closed** 2022-09-28 20:13 UTC
Labels: bug, pending-answer
