### ISSUE TITLE
encoding error

### ISSUE THREAD

**Issue by Philippe-M** [PyFPDF/fpdf2#415] opened 2022-05-05 15:28 UTC
Hello,

I have a problem encoding the character \u202f. The problem appears when converting from us_US to fr_FR, i.e. 4399.99 to 4 684,99

With this code

```python
#!/usr/bin/python
# -*- coding: utf-8 -*-

import sys
from fpdf import FPDF
from fpdf.enums import XPos, YPos
import locale

locale.setlocale(locale.LC_ALL, '')
locale.setlocale(locale.LC_NUMERIC, 'fr_FR.UTF-8')

def main(argv=None):
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("helvetica", size=16)
    s1_vatgro = 4399.99
    pdf.cell(20, 5, check0(s1_vatgro), border="LRB", align="R")
    pdf.output("/tmp/test.pdf")

# Controls the type of the variable value and
# transforms the decimal separator of . to , and
# adds the thousands separator
def check0(value):
    if type(value) is float:
        print("----------------")
        print("it's a float : " + str(value))
        print("Add french decimal serapator and space : " + str(locale.format_string('%.2f', value, grouping=True)))
        print("----------------")
        return locale.format_string('%.2f', value, grouping=True)
    elif type(value) is int:
        print("it's a int")
    elif type(value) is str:
        print("----------------")
        print("it's a string string : " + str(locale.format_string('%.2f', locale.atof(value), grouping=True)))
        print("----------------")
        return str(locale.format_string('%.2f', locale.atof(value), grouping=True))
    else:
        print("????")

if __name__ == "__main__":
        main(sys.argv)
```

I get the error

```
./test.py 
----------------
it's a float : 4399.99
Add french decimal serapator and space : 4 399,99
----------------
Traceback (most recent call last):
  File "/home/xxxxxx/.local/lib/python3.10/site-packages/fpdf/fpdf.py", line 3372, in normalize_text
    return txt.encode(self.core_fonts_encoding).decode("latin-1")
UnicodeEncodeError: 'latin-1' codec can't encode character '\u202f' in position 1: ordinal not in range(256)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/xxxx/Scripts/x3topdf/./test.py", line 41, in <module>
    main(sys.argv)
  File "/home/xxx/Scripts/x3topdf/./test.py", line 17, in main
    pdf.cell(20, 5, check0(s1_vatgro), border="LRB", align="R")
  File "/home/xxx/.local/lib/python3.10/site-packages/fpdf/fpdf.py", line 257, in wrapper
    return fn(self, *args, **kwargs)
  File "/home/xxx/.local/lib/python3.10/site-packages/fpdf/fpdf.py", line 2272, in cell
    txt = self.normalize_text(txt)
  File "/home/xxx/.local/lib/python3.10/site-packages/fpdf/fpdf.py", line 3374, in normalize_text
    raise FPDFUnicodeEncodingException(
fpdf.errors.FPDFUnicodeEncodingException: Character " " at index 1 in text is outside the range of characters supported by the font used: "helvetica". Please consider using a font that supports UTF-8 encoding.
```

**Environment**
* OS : linux Fedora 35
* Python 3.10.4
* `fpdf2` 2.5.3

**Comment by Lucas-C** [comment] 2022-05-05 17:31
Hi and thanks for reporting your issue.

Could you provide some [minimal, autonomous, Python code reproducing your issue](https://stackoverflow.com/help/minimal-reproducible-example) please?
Currently, in the code you provided, I have no idea of what could be the return value of `tools.check0(self.tools, s1_vatgro)`...

`\u202f` is the unicode character named [NARROW NO-BREAK SPACE](https://www.fileformat.info/info/unicode/char/202f/index.htm).
You will need to use a TrueType/OpenType font to render it.
Are you already calling [add_font()](https://pyfpdf.github.io/fpdf2/fpdf/fpdf.html#fpdf.fpdf.FPDF.add_font)?
If so, what font are you currently using?

**Comment by Philippe-M** [comment] 2022-05-06 06:21
Hi @Lucas-C, 

Sorry, I corrected my original post with a code to reproduce the error.

> Are you already calling [add_font()](https://pyfpdf.github.io/fpdf2/fpdf/fpdf.html#fpdf.fpdf.FPDF.add_font)?

I tried to implement it last night without success so far.

**Comment by Lucas-C** [comment] 2022-05-06 11:25
Interesting: on my computer your code works does not crash!
It produces the following file: [issue_415.pdf](https://github.com/PyFPDF/fpdf2/files/8639583/issue_415.pdf)

I think you should track down where this `\u202f` character comes from.
Can you spot non-ascii characters it if you call `cat vET test.py`?

**Comment by gmischler** [comment] 2022-05-07 20:51
> I think you should track down where this `\u202f` character comes from. Can you spot non-ascii characters if you call `cat -vET test.py`?

That seems to be the thousands seperator after locale formatting.
What that does, depends on how exactly 'fr_FR.UTF-8' is configured on your system.

```python
>>> import locale
>>> locale.setlocale(locale.LC_NUMERIC, 'fr_FR.UTF-8')
'fr_FR.UTF-8'
>>> locale.format_string('%.2f', 4399.99, grouping=True)
'4\xa0399,99'
>>> import pprint
>>> pprint.pprint(locale.localeconv())
{'currency_symbol': '',
 'decimal_point': ',',
 'frac_digits': 127,
 'grouping': [3, 0],
 'int_curr_symbol': '',
 'int_frac_digits': 127,
 'mon_decimal_point': '',
 'mon_grouping': [],
 'mon_thousands_sep': '',
 'n_cs_precedes': 127,
 'n_sep_by_space': 127,
 'n_sign_posn': 127,
 'negative_sign': '',
 'p_cs_precedes': 127,
 'p_sep_by_space': 127,
 'p_sign_posn': 127,
 'positive_sign': '',
 'thousands_sep': '\xa0'}
>>> import unicodedata
>>> unicodedata.name('\xa0')
'NO-BREAK SPACE'

```

On @Philippe-M s Fedora, `'thousands_sep'` is apparently set to `'\u202f': 'NARROW NO-BREAK SPACE'`.

**Comment by Philippe-M** [comment] 2022-05-09 07:46
On my Fedora i've this


```
>>> import locale
>>> locale.setlocale(locale.LC_NUMERIC, 'fr_FR.UTF-8')
'fr_FR.UTF-8'
>>> locale.format_string('%.2f', 4399.99, grouping=True)
'4\u202f399,99'
>>> import pprint
>>> pprint.pprint(locale.localeconv())
{'currency_symbol': '',
 'decimal_point': ',',
 'frac_digits': 127,
 'grouping': [3, 0],
 'int_curr_symbol': '',
 'int_frac_digits': 127,
 'mon_decimal_point': '',
 'mon_grouping': [],
 'mon_thousands_sep': '',
 'n_cs_precedes': 127,
 'n_sep_by_space': 127,
 'n_sign_posn': 127,
 'negative_sign': '',
 'p_cs_precedes': 127,
 'p_sep_by_space': 127,
 'p_sign_posn': 127,
 'positive_sign': '',
 'thousands_sep': '\u202f'}
>>> import unicodedata
>>> unicodedata.name('\u202f')
'NARROW NO-BREAK SPACE'
```

**Comment by Lucas-C** [comment] 2022-05-09 08:04
Good catch!

So @Philippe-M you can either change this setting, or use a font file: I have tested the following code using [DejaVuSans.ttf](https://github.com/PyFPDF/fpdf2/blob/master/test/fonts/DejaVuSans.ttf) and it works fine:
```python
from fpdf import FPDF

pdf = FPDF()
pdf.add_page()
pdf.add_font("DejaVuSans", fname="test/fonts/DejaVuSans.ttf")
pdf.set_font("DejaVuSans", size=16)
pdf.cell(20, 5, "AB\u202fC", border="LRB", align="R")
pdf.output("issue_415.pdf")
```

**Comment by Philippe-M** [comment] 2022-05-09 08:58
@Lucas-C 

I'm testing with thist code, and it's ok now

```python
#!/usr/bin/python
# -*- coding: utf-8 -*-

import sys
from fpdf import FPDF
from fpdf.enums import XPos, YPos
import locale

locale.setlocale(locale.LC_ALL, '')
locale.setlocale(locale.LC_NUMERIC, 'fr_FR.UTF-8')

def main(argv=None):
    pdf = FPDF()
    pdf.add_page()
    pdf.add_font('DejaVu', fname="/home/pmaladjian/Scripts/x3topdf/assets/DejaVuSans.ttf")
    pdf.add_font('DejaVub', fname="/home/pmaladjian/Scripts/x3topdf/assets/DejaVuSans-Bold.ttf")
    pdf.set_font("DejaVu", size=16)
    pdf.cell(20, 5, check0("4399.99"), align="R")
    pdf.ln()
    pdf.set_font("DejaVub", size=16)
    pdf.cell(20, 5, check0("4399.99"), align="R")

    pdf.output("/tmp/test.pdf")

# Controls the type of the variable value and
# transforms the decimal separator of . to , and
# adds the thousands separator
def check0(value):
    if type(value) is float:
        print("----------------")
        print("it's a float : " + str(value))
        print("Add french decimal serapator and space : " + str(locale.format_string('%.2f', value, grouping=True)))
        print("----------------")
        return locale.format_string('%.2f', value, grouping=True)
    elif type(value) is int:
        print("it's a int")
    elif type(value) is str:
        print("----------------")
        print("it's a string string : " + str(locale.format_string('%.2f', locale.atof(value), grouping=True)))
        print("----------------")
        return str(locale.format_string('%.2f', locale.atof(value), grouping=True))
    else:
        print("????")

if __name__ == "__main__":
        main(sys.argv)
```

**Comment by Lucas-C** [comment] 2022-05-09 09:00
Wonderful!
Glad you solved your issue 😊
Closing this issue now

**Closed by Lucas-C** 2022-05-09 09:00 UTC
Labels: bug, unicode
